<?php
include ("../database/connection.php");

$display = '';
$display .= '<div class="container-fluid">';
  $display .= '<div class="row">';//DASHBOARD HEADER START
    $display .= '<div class="col-md-12">';
      $display .= '<h2 class="page-title">Dashboard</h2>';
    $display .= '</div>';
  $display .= '</div>';//DASHBOARD HEADER END
  $display .= '<div class="row">'; //CPU INFO BOX START
    $display .= '<div class="info-box">';
        $display .= '<span class="info-box-icon bg-aqua">';
          $display .= '<i class="ui icon microchip"></i>';
        $display .= '</span>';
        $display .= '<div class="info-box-content">';
            $display .= '<div class="progress-group">';
              $display .= '<div class="stats_d">';
                $display .= '<table class="table responsive">';
                  $display .= '<thead>';
                    $display .= '<tr>';
                      $display .= '<th class="text-left">Total</th>';
                      $display .= '<th class="text-left">Deployed</th>';
                      $display .= '<th class="text-left">Defective</th>';
                      $display .= '<th class="text-left">In Stock</th>';
                    $display .= '</tr>';
                  $display .= '</thead>';
                  $display .= '<tbody>';
                    $display .= '<tr>';
                      $display .= '<td class="text-left">15</td>';
                      $display .= '<td class="text-left">5</td>';
                      $display .= '<td class="text-left">5</td>';
                      $display .= '<td class="text-left">5</td>';
                    $display .= '</tr>';
                  $display .= '</tbody>';
                $display .= '</table>';
              $display .= '</div>';
            $display .= '</div>';
        $display .= '</div>';
    $display .= '</div>';
  $display .= '</div>';//CPU INFO BOX END
  $display .= '<div class="row">'; //MONITOR INFO BOX START
    $display .= '<div class="info-box">';
        $display .= '<span class="info-box-icon bg-aqua">';
          $display .= '<i class="ui icon desktop"></i>';
        $display .= '</span>';
        $display .= '<div class="info-box-content">';
            $display .= '<div class="progress-group">';
              $display .= '<div class="stats_d">';
                $display .= '<table class="table responsive">';
                  $display .= '<thead>';
                    $display .= '<tr>';
                      $display .= '<th class="text-left">Total</th>';
                      $display .= '<th class="text-left">Deployed</th>';
                      $display .= '<th class="text-left">Defective</th>';
                      $display .= '<th class="text-left">In Stock</th>';
                    $display .= '</tr>';
                  $display .= '</thead>';
                  $display .= '<tbody>';
                    $display .= '<tr>';
                      $display .= '<td class="text-left">15</td>';
                      $display .= '<td class="text-left">5</td>';
                      $display .= '<td class="text-left">5</td>';
                      $display .= '<td class="text-left">5</td>';
                    $display .= '</tr>';
                  $display .= '</tbody>';
                $display .= '</table>';
              $display .= '</div>';
            $display .= '</div>';
        $display .= '</div>';
    $display .= '</div>';
  $display .= '</div>';//HEADSET INFO BOX END
  $display .= '<div class="row">'; //HEADSET INFO BOX START
    $display .= '<div class="info-box">';
        $display .= '<span class="info-box-icon bg-aqua">';
          $display .= '<i class="ui icon headphones"></i>';
        $display .= '</span>';
        $display .= '<div class="info-box-content">';
            $display .= '<div class="progress-group">';
              $display .= '<div class="stats_d">';
                $display .= '<table class="table responsive">';
                  $display .= '<thead>';
                    $display .= '<tr>';
                      $display .= '<th class="text-left">Total</th>';
                      $display .= '<th class="text-left">Deployed</th>';
                      $display .= '<th class="text-left">Defective</th>';
                      $display .= '<th class="text-left">In Stock</th>';
                    $display .= '</tr>';
                  $display .= '</thead>';
                  $display .= '<tbody>';
                    $display .= '<tr>';
                      $display .= '<td class="text-left">15</td>';
                      $display .= '<td class="text-left">5</td>';
                      $display .= '<td class="text-left">5</td>';
                      $display .= '<td class="text-left">5</td>';
                    $display .= '</tr>';
                  $display .= '</tbody>';
                $display .= '</table>';
              $display .= '</div>';
            $display .= '</div>';
        $display .= '</div>';
    $display .= '</div>';
  $display .= '</div>';//HEADSET INFO BOX END
  $display .= '<div class="row">'; //KEYBOARD INFO BOX START
    $display .= '<div class="info-box">';
        $display .= '<span class="info-box-icon bg-aqua">';
          $display .= '<i class="ui icon keyboard"></i>';
        $display .= '</span>';
        $display .= '<div class="info-box-content">';
            $display .= '<div class="progress-group">';
              $display .= '<div class="stats_d">';
                $display .= '<table class="table responsive">';
                  $display .= '<thead>';
                    $display .= '<tr>';
                      $display .= '<th class="text-left">Total</th>';
                      $display .= '<th class="text-left">Deployed</th>';
                      $display .= '<th class="text-left">Defective</th>';
                      $display .= '<th class="text-left">In Stock</th>';
                    $display .= '</tr>';
                  $display .= '</thead>';
                  $display .= '<tbody>';
                    $display .= '<tr>';
                      $display .= '<td class="text-left">15</td>';
                      $display .= '<td class="text-left">5</td>';
                      $display .= '<td class="text-left">5</td>';
                      $display .= '<td class="text-left">5</td>';
                    $display .= '</tr>';
                  $display .= '</tbody>';
                $display .= '</table>';
              $display .= '</div>';
            $display .= '</div>';
        $display .= '</div>';
    $display .= '</div>';
  $display .= '</div>';//KEYBOARD INFO BOX END
  $display .= '<div class="row">'; //MOUSE INFO BOX START
    $display .= '<div class="info-box">';
        $display .= '<span class="info-box-icon bg-aqua">';
          $display .= '<i class="ui icon mouse pointer"></i>';
        $display .= '</span>';
        $display .= '<div class="info-box-content">';
            $display .= '<div class="progress-group">';
              $display .= '<div class="stats_d">';
                $display .= '<table class="table responsive">';
                  $display .= '<thead>';
                    $display .= '<tr>';
                      $display .= '<th class="text-left">Total</th>';
                      $display .= '<th class="text-left">Deployed</th>';
                      $display .= '<th class="text-left">Defective</th>';
                      $display .= '<th class="text-left">In Stock</th>';
                    $display .= '</tr>';
                  $display .= '</thead>';
                  $display .= '<tbody>';
                    $display .= '<tr>';
                      $display .= '<td class="text-left">15</td>';
                      $display .= '<td class="text-left">5</td>';
                      $display .= '<td class="text-left">5</td>';
                      $display .= '<td class="text-left">5</td>';
                    $display .= '</tr>';
                  $display .= '</tbody>';
                $display .= '</table>';
              $display .= '</div>';
            $display .= '</div>';
        $display .= '</div>';
    $display .= '</div>';
  $display .= '</div>';//MOUSE INFO BOX END
  $display .= '<div class="row">'; //UPS INFO BOX START
    $display .= '<div class="info-box">';
        $display .= '<span class="info-box-icon bg-aqua">';
          $display .= '<i class="ui icon plug"></i>';
        $display .= '</span>';
        $display .= '<div class="info-box-content">';
            $display .= '<div class="progress-group">';
              $display .= '<div class="stats_d">';
                $display .= '<table class="table responsive">';
                  $display .= '<thead>';
                    $display .= '<tr>';
                      $display .= '<th class="text-left">Total</th>';
                      $display .= '<th class="text-left">Deployed</th>';
                      $display .= '<th class="text-left">Defective</th>';
                      $display .= '<th class="text-left">In Stock</th>';
                    $display .= '</tr>';
                  $display .= '</thead>';
                  $display .= '<tbody>';
                    $display .= '<tr>';
                      $display .= '<td class="text-left">15</td>';
                      $display .= '<td class="text-left">5</td>';
                      $display .= '<td class="text-left">5</td>';
                      $display .= '<td class="text-left">5</td>';
                    $display .= '</tr>';
                  $display .= '</tbody>';
                $display .= '</table>';
              $display .= '</div>';
            $display .= '</div>';
        $display .= '</div>';
    $display .= '</div>';
  $display .= '</div>';//UPS INFO BOX END
  $display .= '<div class="row">'; //ROUTER INFO BOX START
    $display .= '<div class="info-box">';
        $display .= '<span class="info-box-icon bg-aqua">';
          $display .= '<i class="ui icon hdd"></i>';
        $display .= '</span>';
        $display .= '<div class="info-box-content">';
            $display .= '<div class="progress-group">';
              $display .= '<div class="stats_d">';
                $display .= '<table class="table responsive">';
                  $display .= '<thead>';
                    $display .= '<tr>';
                      $display .= '<th class="text-left">Total</th>';
                      $display .= '<th class="text-left">Deployed</th>';
                      $display .= '<th class="text-left">Defective</th>';
                      $display .= '<th class="text-left">In Stock</th>';
                    $display .= '</tr>';
                  $display .= '</thead>';
                  $display .= '<tbody>';
                    $display .= '<tr>';
                      $display .= '<td class="text-left">15</td>';
                      $display .= '<td class="text-left">5</td>';
                      $display .= '<td class="text-left">5</td>';
                      $display .= '<td class="text-left">5</td>';
                    $display .= '</tr>';
                  $display .= '</tbody>';
                $display .= '</table>';
              $display .= '</div>';
            $display .= '</div>';
        $display .= '</div>';
    $display .= '</div>';
  $display .= '</div>';//ROUTER INFO BOX END
  $display .= '<div class="row">'; //SWITCH INFO BOX START
    $display .= '<div class="info-box">';
        $display .= '<span class="info-box-icon bg-aqua">';
          $display .= '<i class="ui icon server"></i>';
        $display .= '</span>';
        $display .= '<div class="info-box-content">';
            $display .= '<div class="progress-group">';
              $display .= '<div class="stats_d">';
                $display .= '<table class="table responsive">';
                  $display .= '<thead>';
                    $display .= '<tr>';
                      $display .= '<th class="text-left">Total</th>';
                      $display .= '<th class="text-left">Deployed</th>';
                      $display .= '<th class="text-left">Defective</th>';
                      $display .= '<th class="text-left">In Stock</th>';
                    $display .= '</tr>';
                  $display .= '</thead>';
                  $display .= '<tbody>';
                    $display .= '<tr>';
                      $display .= '<td class="text-left">15</td>';
                      $display .= '<td class="text-left">5</td>';
                      $display .= '<td class="text-left">5</td>';
                      $display .= '<td class="text-left">5</td>';
                    $display .= '</tr>';
                  $display .= '</tbody>';
                $display .= '</table>';
              $display .= '</div>';
            $display .= '</div>';
        $display .= '</div>';
    $display .= '</div>';
  $display .= '</div>';//SWITCH INFO BOX END
$display .= '</div>';

echo $display;

 ?>
